# This is NumPy Library Session

Array Creation 

In [43]:
import numpy as np

a = np.ones((3, 4)) #(3:rows, 4:columns)
print(a)

b = np.zeros((3, 3))
print(b)

c = np.eye(3) # Identity matrix, diagonal of ones
print(c) 

d = np.array([[1, 2],[3, 4], [5, 6]], dtype=np.float32)
print(d)

e1 = np.random.random(3) # Random 3 numbers between 0 and 1
print(e1)

e2 = np.random.rand(3, 4) # random a matrix of 3x4 with numbers btw 0 and 1
print(e2)

e3 = np.random.randint(0, 10, (3,3)) # random a matrix 3x3 of numbers btw 0 and 10
print(e3)

e4 = np.random.normal(0, 1, (3,3)) # random a matrox 3x3 of numbers with normal distribution (mean=0, std=1)
print(e4)
print(e4.mean(), e4.var(), e4.std()) # print the normal distribution stats (mean, variance, standard deviation)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[0.26014275 0.15711637 0.34303444]
[[0.15757248 0.31298792 0.02871013 0.45507659]
 [0.49951784 0.67392226 0.24194912 0.79529898]
 [0.07296576 0.96321157 0.92432825 0.73351531]]
[[5 8 1]
 [3 7 8]
 [1 4 1]]
[[ 0.98319323 -2.12871827 -1.55703453]
 [ 1.74972877  0.1044773   1.55946532]
 [ 0.45985086  0.17291156  1.04370347]]
0.26528641207902387 1.5693501679575046 1.2527370705608998


operations on array

In [44]:
# Arrays addition
A = np.ones((2, 3))
B = np.ones((2, 3))
C = A + B # element-wise addition, but must match the same shape
print(C)

# Arrays reshaping
D = np.array([[1, 2, 3], [4, 5, 6]])
print(D)
print(D.shape) # (2, 3)

D = D.reshape((3, 2)) #notes u can only reshape array while total no of elements matches or will give error 
print(D)

D = D.flatten() # convert from matrix to a row vector
print(D)
print(D.shape) # (6, ) -> invalid shape it have to be reshaped 
D = D.reshape((1,6))
print(D)
print(D.shape) # (6, 1) -> valid shape

# Transpose matrix
v = np.random.randint(0, 10, (3, 4))
print(v)

v_t = v.T
print(v_t)

[[2. 2. 2.]
 [2. 2. 2.]]
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[9 0 6 5]
 [5 5 4 5]
 [6 1 3 0]]
[[9 5 6]
 [0 5 1]
 [6 4 3]
 [5 5 0]]


Operations using matrices

In [45]:
# Matrix Arithmetic Operations
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

# Matrix Multiplication
z = x.dot(y)
print(z)

# Logical Operations
print(z > 20) # array of T/F whether each element in the matrix z is > 20 T or F

# Scalar Operations
print(z + 10)  # add 10 to each element in z matrix

# Mathematical Functions
print(np.sin(z))
print(np.log(z))
print(np.exp(z))
print(np.sqrt(z))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[False  True]
 [ True  True]]
[[29 32]
 [53 60]]
[[ 0.14987721 -0.00885131]
 [-0.83177474 -0.26237485]]
[[2.94443898 3.09104245]
 [3.76120012 3.91202301]]
[[1.78482301e+08 3.58491285e+09]
 [4.72783947e+18 5.18470553e+21]]
[[4.35889894 4.69041576]
 [6.55743852 7.07106781]]


Slicing

In [46]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# Slicing
print(A[0, :]) # 1st row
print(A[:, 0]) # 1st column
print(A[1,1]) # element at 2nd row, 2nd column

print(A[A > 5]) # elements greater than 5

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
5
[6 7 8 9]


Broadcasting

In [47]:
A = np.random.randint(0, 10, (5, 5, 3))
print(A.shape)

B = np.array([1, 0, 1])
print(B.shape)

C = A + B
print(C)
print(C.shape)

(5, 5, 3)
(3,)
[[[ 5  6  7]
  [ 9  9  6]
  [ 1  7  1]
  [ 2  7  6]
  [ 1  8  2]]

 [[ 7  5  2]
  [ 3  2  7]
  [10  7  6]
  [10  4  8]
  [10  4  8]]

 [[ 1  3  4]
  [ 1  1  7]
  [ 7  4  7]
  [ 8  2 10]
  [ 1  8  4]]

 [[ 6  7  4]
  [ 4  5 10]
  [ 1  4  9]
  [ 4  6  5]
  [ 6  1  8]]

 [[ 6  6 10]
  [ 3  6  4]
  [ 7  5  5]
  [ 1  8  8]
  [ 9  7  6]]]
(5, 5, 3)
